---

- name: ensure pod conf dir exists
  file:
    path: "{{ awx_pod_yaml_dir }}"
    state: directory

- name: do preparations for running pod
  block:

  - name: "set AWX configuration file: {{ awx_pod_yaml_path }}"
    template:
      src: awx.yml.j2
      dest: "{{ awx_pod_yaml_path }}"
      owner: root
      group: root
      mode: "0600"

  - name: ensure postgres exported volume directory exists
    file:
      path: "{{ awx_db_volume_host_path }}"
      state: directory
      mode: "0700"
      owner: root

  - name: ensure awx exported volume directory exists
    file:
      path: "{{ awx_data_volume_host_path }}"
      state: directory
      mode: "0700"
      owner: 1000

  - name: ensure awxweb nginx volume directory exists
    file:
      path: "{{ awx_nginx_volume_host_path }}"
      state: directory
      mode: "0700"
      owner: 1000

  - name: ensure awx secret volume directory exists
    file:
      path: "{{ awx_secret_volume_host_path }}"
      state: directory
      mode: "0700"
      owner: 1000

  - name: copy awx SECRET_FILE
    copy:
      content: iamverysecret
      dest: "{{ awx_secret_volume_host_path }}/SECRET_FILE"
      mode: "0600"
      owner: 1000

  - name: overwrite containers ngnix.conf (to run on port 8052)
    copy:
      src: nginx.conf
      dest: "{{ awx_nginx_volume_host_path }}/nginx.conf"
      mode: "0600"
      owner: 1000

  when: container_state == "running"

- name: import role podman_container_systemd to handle containers
  vars:
    container_name: "{{ awx_pod_name }}"
    container_state: running
    container_pod_yaml: "{{ awx_pod_yaml_path }}"
    container_image_list: "{{ awx_container_image_list }}"
    container_firewall_ports:
      - "{{ awx_host_port }}/tcp"
  import_role:
    name: podman_container_systemd

- name: "remove AWX configuration file: {{ awx_pod_yaml_path }}"
  file:
    path: "{{ awx_pod_yaml_path }}"
    state: absent
  when: container_state == "absent"

- name: "remove awx secret directory: {{ awx_secret_volume_host_path }}"
  file:
    path: "{{ awx_secret_volume_host_path }}/"
    state: absent
  when: container_state == "absent"

- name: "remove nginx configuration directory: {{ awx_nginx_volume_host_path }}"
  file:
    path: "{{ awx_nginx_volume_host_path }}/"
    state: absent
  when: container_state == "absent"
